INSERT INTO `Genre` (`GenreId`, `Name`) VALUES (1, 'Action');
INSERT INTO `Genre` (`GenreId`, `Name`) VALUES (2, 'Adventure');
INSERT INTO `Genre` (`GenreId`, `Name`) VALUES (3, 'Animation');
INSERT INTO `Genre` (`GenreId`, `Name`) VALUES (4, 'Comedy');
INSERT INTO `Genre` (`GenreId`, `Name`) VALUES (5, 'Crime');
INSERT INTO `Genre` (`GenreId`, `Name`) VALUES (6, 'Drama');
INSERT INTO `Genre` (`GenreId`, `Name`) VALUES (7, 'Fantasy');
INSERT INTO `Genre` (`GenreId`, `Name`) VALUES (8, 'Historical');
INSERT INTO `Genre` (`GenreId`, `Name`) VALUES (9, 'Historical fiction');
INSERT INTO `Genre` (`GenreId`, `Name`) VALUES (10, 'Horror');
INSERT INTO `Genre` (`GenreId`, `Name`) VALUES (11, 'Magical realism');
INSERT INTO `Genre` (`GenreId`, `Name`) VALUES (12, 'Mystery');
INSERT INTO `Genre` (`GenreId`, `Name`) VALUES (13, 'Paranoid Fiction');
INSERT INTO `Genre` (`GenreId`, `Name`) VALUES (14, 'Philosophical');
INSERT INTO `Genre` (`GenreId`, `Name`) VALUES (15, 'Political');
INSERT INTO `Genre` (`GenreId`, `Name`) VALUES (16, 'Romance');
INSERT INTO `Genre` (`GenreId`, `Name`) VALUES (17, 'Saga');
INSERT INTO `Genre` (`GenreId`, `Name`) VALUES (18, 'Satire');
INSERT INTO `Genre` (`GenreId`, `Name`) VALUES (19, 'Science fiction');
INSERT INTO `Genre` (`GenreId`, `Name`) VALUES (20, 'Social');
INSERT INTO `Genre` (`GenreId`, `Name`) VALUES (21, 'Speculative');
INSERT INTO `Genre` (`GenreId`, `Name`) VALUES (22, 'Thriller');
INSERT INTO `Genre` (`GenreId`, `Name`) VALUES (23, 'Urban');
INSERT INTO `Genre` (`GenreId`, `Name`) VALUES (24, 'Western');